// packages/svelte-demo/src/App.svelte
<script lang="ts">
  let displayText = false;

  function handleButtonClick(){
    displayText = true;
  }
</script>

<main>
  <article id="display">
    {#if displayText}
      <p class="display-text">Welcome to wonderland!</p>
    {/if}
  </article>
  <button id="display-action-button" on:click={handleButtonClick}>Click me!</button>
</main>

<style>
  .display-text {
    display: block;
    text-align: center;
    font-size: 23px;
  }
</style>

// packages/react-demo/src/App.tsx
import { useState } from 'react';
import './App.css';

function App() {
  const [displayText, setDisplayText] = useState(false);

  return (
    <div className="App">
      <article id="display">
        {displayText && (
          <p className="display-text">Welcome to wonderland!</p>
        )}
      </article>
      <button id="display-action-button" onClick={() => {
        setDisplayText(true);
      }}>Click me!</button>
    </div>
  )
}

export default App
